### ISSUE TITLE
Progress bar not displaying % correctly

### ISSUE THREAD

**Issue by rongsheng** [Secretmapper/combustion#15]
![image](https://cloud.githubusercontent.com/assets/703743/25306094/ed008e18-27c9-11e7-9bae-96371b213720.png)

I think this should be in percentage rather than in pixels?

https://github.com/Secretmapper/combustion/blob/master/src/components/Torrent/ProgressBar/index.js#L53

style={{ width: getPercentage(torrent).toString() + '%' }}

**Comment by Xiretza** [comment]
Uhm, why was this closed? As far as I can see nothing was fixed.

**Comment by kingsleyadam** [comment]
Vote to re-open. This is still an issue. Changing the value from pixel to percentage fixed it for me.
